-- CampanhaHub · schema inicial (Postgres / Supabase)
-- Senhas entram só como hash bcrypt ($2b$...), nunca em texto puro.

create extension if not exists pgcrypto;

create table if not exists users (
  id integer generated by default as identity primary key,
  name varchar(120) not null,
  email varchar(180) not null unique,
  hashed_password varchar(255) not null,
  created_at timestamptz not null default now(),
  constraint users_password_is_bcrypt check (
    hashed_password like '$2a$%'
    or hashed_password like '$2b$%'
    or hashed_password like '$2y$%'
  )
);

create table if not exists clients (
  id integer generated by default as identity primary key,
  user_id integer not null references users (id),
  name varchar(160) not null,
  segment varchar(120) not null default '',
  description text not null default '',
  contact_email varchar(180) not null default '',
  contact_phone varchar(40) not null default '',
  status varchar(20) not null default 'ativo',
  created_at timestamptz not null default now()
);

create table if not exists platforms (
  id integer generated by default as identity primary key,
  user_id integer not null references users (id),
  name varchar(80) not null,
  description varchar(255) not null default '',
  created_at timestamptz not null default now(),
  constraint uq_platform_user_name unique (user_id, name)
);

create table if not exists campaigns (
  id integer generated by default as identity primary key,
  user_id integer not null references users (id),
  client_id integer not null references clients (id),
  platform_id integer not null references platforms (id),
  name varchar(160) not null,
  objective varchar(160) not null default '',
  description text not null default '',
  start_date date not null,
  end_date date,
  budget double precision not null default 0,
  status varchar(20) not null default 'rascunho',
  created_at timestamptz not null default now()
);

create table if not exists contents (
  id integer generated by default as identity primary key,
  campaign_id integer not null references campaigns (id) on delete cascade,
  title varchar(180) not null,
  content_type varchar(60) not null default 'post',
  scheduled_date date not null,
  status varchar(20) not null default 'planejado',
  notes text not null default '',
  created_at timestamptz not null default now()
);

create table if not exists metrics (
  id integer generated by default as identity primary key,
  campaign_id integer not null references campaigns (id) on delete cascade,
  date date not null,
  reach integer not null default 0,
  impressions integer not null default 0,
  clicks integer not null default 0,
  likes integer not null default 0,
  comments integer not null default 0,
  shares integer not null default 0,
  conversions integer not null default 0,
  investment double precision not null default 0,
  created_at timestamptz not null default now()
);

create table if not exists expenses (
  id integer generated by default as identity primary key,
  campaign_id integer not null references campaigns (id) on delete cascade,
  description varchar(180) not null,
  amount double precision not null,
  date date not null,
  category varchar(80) not null default 'mídia',
  created_at timestamptz not null default now()
);

create index if not exists ix_users_email on users (email);
create index if not exists ix_clients_user_id on clients (user_id);
create index if not exists ix_platforms_user_id on platforms (user_id);
create index if not exists ix_campaigns_user_id on campaigns (user_id);
create index if not exists ix_campaigns_client_id on campaigns (client_id);
create index if not exists ix_campaigns_platform_id on campaigns (platform_id);
create index if not exists ix_contents_campaign_id on contents (campaign_id);
create index if not exists ix_metrics_campaign_id on metrics (campaign_id);
create index if not exists ix_expenses_campaign_id on expenses (campaign_id);

alter table users enable row level security;
alter table clients enable row level security;
alter table platforms enable row level security;
alter table campaigns enable row level security;
alter table contents enable row level security;
alter table metrics enable row level security;
alter table expenses enable row level security;
