-- Plano da marca, meta da campanha, CAC e registros de palavra-chave e experimento.

alter table clients add column if not exists positioning text not null default '';
alter table clients add column if not exists swot_strengths text not null default '';
alter table clients add column if not exists swot_weaknesses text not null default '';
alter table clients add column if not exists swot_opportunities text not null default '';
alter table clients add column if not exists swot_threats text not null default '';
alter table clients add column if not exists audience_geo text not null default '';
alter table clients add column if not exists audience_demo text not null default '';
alter table clients add column if not exists audience_behavior text not null default '';
alter table clients add column if not exists audience_psycho text not null default '';
alter table clients add column if not exists persona text not null default '';

alter table campaigns add column if not exists goal_metric varchar(40) not null default '';
alter table campaigns add column if not exists goal_value double precision not null default 0;
alter table campaigns add column if not exists strategy varchar(40) not null default '';
alter table campaigns add column if not exists reference_notes text not null default '';

alter table contents add column if not exists owner varchar(120) not null default '';
alter table contents add column if not exists approach text not null default '';
alter table contents add column if not exists estimated_cost double precision not null default 0;

alter table metrics add column if not exists new_customers integer not null default 0;

create table if not exists keywords (
  id integer generated by default as identity primary key,
  campaign_id integer not null references campaigns (id) on delete cascade,
  term varchar(160) not null,
  intent varchar(160) not null default '',
  target_url varchar(300) not null default '',
  notes text not null default '',
  created_at timestamptz not null default now()
);

create table if not exists experiments (
  id integer generated by default as identity primary key,
  campaign_id integer not null references campaigns (id) on delete cascade,
  hypothesis text not null,
  metric_name varchar(80) not null default '',
  status varchar(20) not null default 'ideia',
  learning text not null default '',
  created_at timestamptz not null default now()
);

create index if not exists ix_keywords_campaign_id on keywords (campaign_id);
create index if not exists ix_experiments_campaign_id on experiments (campaign_id);

alter table keywords enable row level security;
alter table experiments enable row level security;
